from __future__ import annotations

from enum import StrEnum


class MarketRegime(StrEnum):
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    RANGE_UNCLEAR = "RANGE_UNCLEAR"
    RISK_OFF = "RISK_OFF"
    SYSTEM_DEGRADED = "SYSTEM_DEGRADED"


class DirectionalState(StrEnum):
    BULLISH_CONTINUATION = "BULLISH_CONTINUATION"
    BULLISH_BREAKOUT = "BULLISH_BREAKOUT"
    BEARISH_CONTINUATION = "BEARISH_CONTINUATION"
    BEARISH_BREAKDOWN = "BEARISH_BREAKDOWN"
    NEUTRAL = "NEUTRAL"
    NO_TRADE = "NO_TRADE"


class IVState(StrEnum):
    IV_RICH = "IV_RICH"
    IV_NORMAL = "IV_NORMAL"
    IV_CHEAP = "IV_CHEAP"


class StrategyType(StrEnum):
    BULL_PUT_SPREAD = "BULL_PUT_SPREAD"
    BEAR_CALL_SPREAD = "BEAR_CALL_SPREAD"
    BULL_CALL_SPREAD = "BULL_CALL_SPREAD"
    BEAR_PUT_SPREAD = "BEAR_PUT_SPREAD"


class SignalState(StrEnum):
    CANDIDATE = "CANDIDATE"
    QUALIFIED = "QUALIFIED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class OrderState(StrEnum):
    ORDER_DRAFTED = "ORDER_DRAFTED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"


class PositionState(StrEnum):
    OPEN = "OPEN"
    EXIT_PENDING = "EXIT_PENDING"
    CLOSED = "CLOSED"
